### ISSUE TITLE
Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by aolchik** [remy/retrobot#1]
Hello,

After starting retrobot, inviting the bot to a channel and issuing @retrobot: start, the agent exists with the following error:

retrobot/lib/index.js:244
      let members = data.channel.members || [];
                        ^

TypeError: Cannot read property 'channel' of undefined
    at slack.channels.info (/Users/aolchik/src/retrobot/lib/index.js:244:25)
    at Request._callback (/Users/aolchik/src/retrobot/node_modules/slack/methods/_exec.js:40:7)
    at Request.self.callback (/Users/aolchik/src/retrobot/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/aolchik/src/retrobot/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/aolchik/src/retrobot/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)

**Comment by remy** [comment]
Can I assume you gave the bot a valid slack token? I can't look at this this second, but certainly debug it tomorrow.

**Comment by aolchik** [comment]
I suppose I did, because the @retrobot: start receives a feedback from the bot that the session is being recorded, then it crashes.

**Comment by remy** [comment]
Okay. I'll take a look at the line in the morning (I'm on UK time). I doubt if it is a factor, but what was the name of the channel that the retrobot was in?

**Comment by aolchik** [comment]
@remy the problem happens only with private channels
In my case this would be a useful feature as I don't want all slack member to have access to each retrospective.

**Comment by remy** [comment]
Ah…I didn't test with a private channel! I'll do some reading and get back to you! Thank you.

**Comment by remy** [comment]
@aolchik okay, I think I can see how to fix this all. One question though: are you intending to use the retrobot for multiple team retros? It's currently coded as a singleton, but if you need to use it as Team A has a retro and Team B has a retro, then I need to make sure the retrospectives don't leak across channels.

**Comment by aolchik** [comment]
@remy, no need to run multiple retrospectives simultaneously. The only
requirement is privacy. The support of retrospectives on private channels,
one at a time, is enough.

Em ter, 23 de ago de 2016 10:04, Remy Sharp notifications@github.com
escreveu:
